version: '3.4'
services:
  mysqlmaster:
    hostname: mysqlmaster
    image: mysql-percona-toolkit:5.7.26
    build:
     context: mysql/
     args:
       - http_proxy=$http_proxy
       - https_proxy=$http_proxy
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql-master:/var/lib/mysql/
      - ./grants/:/docker-entrypoint-initdb.d/
      - ./config/mysql-master:/etc/mysql/conf.d/
    networks:
       cluster:
          ipv4_address: 172.56.0.2

  mysqlslave:
    hostname: mysqlslave
    image: mysql-percona-toolkit:5.7.26
    build:
     context: mysql/
     args:
       - http_proxy=$http_proxy
       - https_proxy=$http_proxy
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_MASTER_HOST: mysqlmaster
       MYSQL_REPLICATION_USER: repl
       MYSQL_REPLICATION_PASSWORD: repl
    volumes:
      - ./data/dump/:/dump
      - ./data/mysql-slave:/var/lib/mysql/
      - ./config/mysql-slave:/etc/mysql/conf.d/
    networks:
       cluster:
          ipv4_address: 172.56.0.3

  proxysql:
    hostname: proxysql
    image: proxysql:latest
    build:
      context: proxysql/
      args:
        - http_proxy=$http_proxy
        - https_proxy=$http_proxy
    ports:
      - 3306:3306
      - 3307:3307
      - 3308:3308
      - 6032:6032
    volumes:
     - ./config/proxysql/proxysql.cnf:/etc/proxysql.cnf
     - ./data/proxysql:/var/lib/proxysql
    command: ['proxysql', '-f', '--reload', '-c', '/etc/proxysql.cnf']
    networks:
      cluster:
         ipv4_address: 172.56.0.4
    depends_on:
       - mysqlmaster
       - mysqlslave

  heartbeat:
   hostname: heartbeat
   image: heartbeat:latest
   build:
     context: heartbeat/
     args:
       - http_proxy=$http_proxy
       - https_proxy=$http_proxy
   networks:
      cluster:
         ipv4_address: 172.56.0.5
   depends_on:
      - proxysql
   environment:
     PT_MASTER: proxysql
     PT_DATABASE: percona
     PT_USER: super
     PT_PASSWORD: superLuser

  orchestrator:
   hostname: orchestrator
   image: orchestrator:latest
   build:
     context: orchestrator/
     args:
       - http_proxy=$http_proxy
       - https_proxy=$http_proxy
   volumes:
    - ./config/orchestrator/orchestrator.conf.json:/etc/orchestrator.conf.json
    - ./data/orchestrator:/app/data
   networks:
      cluster:
         ipv4_address: 172.56.0.7
   ports:
    - "3000:3000"

networks:
  cluster:
    ipam:
      driver: default
      config:
      - subnet: 172.56.0.0/16
