name: MySQL HA Push packages

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  MYSQL_FULL_IMAGE_NAME: garutilorenzo/mysql-gtid-replication:latest
  HEARTBEAT_FULL_IMAGE_NAME: garutilorenzo/heartbeat:latest

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: docker-compose -f .docker-compose.yml-ci build --pull --no-cache
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          MYSQL_IMAGE_NAME=${MYSQL_FULL_IMAGE_NAME#*/}
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$MYSQL_IMAGE_NAME
          echo MYSQL_IMAGE_NAME=$MYSQL_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $MYSQL_FULL_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
      - name: Push image
        run: |
          HEARTBEAT_IMAGE_NAME=${HEARTBEAT_FULL_IMAGE_NAME#*/}
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$HEARTBEAT_IMAGE_NAME
          echo HEARTBEAT_IMAGE_NAME=$HEARTBEAT_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $HEARTBEAT_FULL_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID